/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graphicalInterface;

import bean.DAO;
import static bean.baglantilar.baglantiOlustur;
import bean.ilac;
import static bean.tablolariDoldurma.anaSayfaStokTablosunuDoldur;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Recep
 */
public class calisanPanel extends javax.swing.JFrame {

    /**
     * Creates new form calisanPanel
     */
    Connection conn;
    LinkedList<ilac> ilaclar = new LinkedList<ilac>();
    LinkedList<Integer> birim = new LinkedList<Integer>();

    public calisanPanel() throws SQLException {
        initComponents();
        conn = baglantiOlustur();
        DefaultTableModel dtm;
        ResultSet rs;
        Statement stmt;
        try {
            stmt = conn.createStatement();
            dtm = (DefaultTableModel) ilacStok.getModel();
            rs = stmt.executeQuery("SELECT * FROM ilaclar");
            while (rs.next()) {
                int ILAC_ID = rs.getInt("ILAC_ID");
                String ADI = rs.getString("ADI");
                int DISTRIBUTOR_ID = rs.getInt("DISTRIBUTOR_ID");
                double FIYAT = rs.getDouble("FIYAT");
                String ADET = rs.getString("ADET");
                dtm.addRow(new Object[]{ILAC_ID, ADI, DISTRIBUTOR_ID, FIYAT, ADET});
            }
        } catch (SQLException ex) {
            Logger.getLogger(anaSayfa.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public calisanPanel(String tc) throws SQLException {
        initComponents();
        calisantcno.setText(tc);
        jLabel10.setText(jLabel10.getText() + "\n");
        conn = baglantiOlustur();
        DefaultTableModel dtm;
        ResultSet rs;
        Statement stmt;
        try {
            stmt = conn.createStatement();
            dtm = (DefaultTableModel) ilacStok.getModel();
            rs = stmt.executeQuery("SELECT * FROM ilaclar");
            while (rs.next()) {
                int ILAC_ID = rs.getInt("ILAC_ID");
                String ADI = rs.getString("ADI");
                int DISTRIBUTOR_ID = rs.getInt("DISTRIBUTOR_ID");
                double FIYAT = rs.getDouble("FIYAT");
                String ADET = rs.getString("ADET");
                dtm.addRow(new Object[]{ILAC_ID, ADI, DISTRIBUTOR_ID, FIYAT, ADET});
            }
        } catch (SQLException ex) {
            Logger.getLogger(anaSayfa.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /*public calisanPanel(String tc) throws SQLException{
        
    }*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        hastatc = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        hastaad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        hastasoyad = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        hastadogum = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ilacStok = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        ilacAdi = new javax.swing.JTextField();
        ilacAra = new javax.swing.JButton();
        calisantcno = new javax.swing.JLabel();
        ilacid = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ilac_id_gir = new javax.swing.JTextField();
        receteyeEkle = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        adet = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("TC Kimlik No");

        jLabel2.setText("Adı");

        jLabel3.setText("Soyadı");

        jLabel4.setText("Doğum Tarihi");

        ilacStok.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "ADI", "DISTRIBUTOR", "FIYAT", "ADET"
            }
        ));
        jScrollPane1.setViewportView(ilacStok);

        jLabel5.setText("İlaçlar");

        ilacAra.setText("Ara");
        ilacAra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ilacAraActionPerformed(evt);
            }
        });

        calisantcno.setText("jLabel6");

        ilacid.setText("Ilac id");

        jLabel7.setText("İlaç Adına Göre Arama Yap");

        jLabel8.setText("İlaç id");

        receteyeEkle.setText("Reçeteye Ekle");
        receteyeEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receteyeEkleActionPerformed(evt);
            }
        });

        jLabel9.setText("İlaçlar");

        jButton2.setText("Bitti");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setText("Adet");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(hastadogum, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(hastatc, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(hastaad, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel4))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(hastasoyad, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel8)
                    .addComponent(ilac_id_gir)
                    .addComponent(receteyeEkle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6)
                    .addComponent(adet)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(calisantcno))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ilacAdi)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ilacAra)
                        .addGap(18, 18, 18)
                        .addComponent(ilacid)
                        .addGap(8, 8, 8)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(calisantcno)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(hastatc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hastaad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hastasoyad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hastadogum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ilac_id_gir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(adet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(receteyeEkle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ilacAdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ilacAra)
                    .addComponent(ilacid))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ilacAraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ilacAraActionPerformed
        String ilacIsım = ilacAdi.getText();
        int sonuc = 0;
        try {
            sonuc = DAO.ilacAra(ilacIsım);
        } catch (SQLException ex) {
            Logger.getLogger(calisanPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        ilacid.setText(String.valueOf(sonuc));
    }//GEN-LAST:event_ilacAraActionPerformed

    private void receteyeEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receteyeEkleActionPerformed
        int id = Integer.parseInt(ilac_id_gir.getText());
        birim.add(Integer.parseInt(adet.getText()));
        Iterator<ilac> iterate = ilaclar.iterator();
        try {
            ilac i = DAO.idTabanliIlacAra(id);
            if (i != null) {
                this.ilaclar.add(i);
            } else {
                JOptionPane.showMessageDialog(null, "Bu id numarasına ait ilaç bulunmamaktadır!");
            }
        } catch (SQLException ex) {
            Logger.getLogger(calisanPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        jLabel10.setText("");
        for (ilac element : ilaclar) {

            jLabel10.setText(jLabel10.getText() + "\n" + element.getAdi() + "\n");
        }
    }//GEN-LAST:event_receteyeEkleActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        double toplamFiyat = 0;
        String calisanTc = calisantcno.getText();
        String hastaTc = hastatc.getText();
        String hastaIsim = hastaad.getText();
        String hastaSoyIsim = hastasoyad.getText();
        String hastaDogumTarihi = hastadogum.getText();
        try {
            DAO.hastaEkle(hastaTc, hastaIsim, hastaSoyIsim, hastaDogumTarihi);
        } catch (SQLException ex) {
            Logger.getLogger(calisanPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        int i = 0;
        while (!ilaclar.isEmpty()) {
            int ilac_id = ilaclar.get(i).getIlac_id();
            int birimm = birim.get(i);
            double fiyat = ilaclar.get(i).getFiyat();
            toplamFiyat += birimm * fiyat;
            try {
                DAO.satisaEkle(calisanTc, hastaTc, ilac_id, birimm, toplamFiyat);
                //DAO.satilanIlacinStogunuAzalt(ilac_id,birimm);
            } catch (SQLException ex) {
                Logger.getLogger(calisanPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
            ilaclar.remove();
            birim.remove();
        }
        ilaclar.clear();
        birim.clear();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calisanPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calisanPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calisanPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calisanPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new calisanPanel().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(calisanPanel.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adet;
    private javax.swing.JLabel calisantcno;
    private javax.swing.JTextField hastaad;
    private javax.swing.JTextField hastadogum;
    private javax.swing.JTextField hastasoyad;
    private javax.swing.JTextField hastatc;
    private javax.swing.JTextField ilacAdi;
    private javax.swing.JButton ilacAra;
    private javax.swing.JTable ilacStok;
    private javax.swing.JTextField ilac_id_gir;
    private javax.swing.JLabel ilacid;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton receteyeEkle;
    // End of variables declaration//GEN-END:variables
}
